DATA:
    ROOT: '/mnt/sdb/data/jingyinuo/animal_kingdom/video'
    TRAIN_FILE: '/mnt/sdb/data/jingyinuo/animal_kingdom/train2_label.txt' #00
    VAL_FILE: '/mnt/sdb/data/jingyinuo/animal_kingdom/test2_label.txt'
    DATASET: 'AK'
    NUM_FRAMES: 16
    NUM_CLASSES: 14
    LABEL_LIST: '/mnt/sdb/data/jingyinuo/animal_kingdom/label2.csv'
    MULTI_CLASSES: True
    NUM_ANIMAL_CLASSES: 958
    ANIMAL_LABEL_LIST: '/mnt/sdb/data/jingyinuo/animal_kingdom/animal_label.csv'
    FEATURE_ROOT: '/mnt/sdb/data/jingyinuo/animal_kingdom/visual_feature'
MODEL:
    ARCH: ViT-B/16
    MODEL_NAME: 'VideoPrompt'
TRAIN:
    BATCH_SIZE:  64
    LOSS: 'ce'
    ACCUMULATION_STEPS: 4
    EPOCHS: 30
    LR: 1e-4
    LR_POLICY: cosineannealingwarmrestarts
    WEIGHT_DECAY: 1e-4
    WEIGHT_DECAY_STEPS: 2e5
    WARMUP_EPOCHS: 4.0
    OPTIMIZER: adamw
NUM_WORKERS: 16