DATA:
    ROOT: '/mnt/sdb/data/jingyinuo/mmnet/trimmed_video'
    TRAIN_FILE: '/mnt/sdb/data/jingyinuo/mmnet/annotation/composition/train.txt' #00 /mnt/sdb/data/jingyinuo/mmnet/annotation/composition/train.csv
    VAL_FILE: '/mnt/sdb/data/jingyinuo/mmnet/annotation/composition/test.txt'
    DATASET: mmnet
    NUM_FRAMES: 8
    NUM_CLASSES: 12
    LABEL_LIST: '/mnt/sdb/data/jingyinuo/mmnet/annotation/behavior_to_id.csv'
    MULTI_CLASSES: False
    NUM_ANIMAL_CLASSES: 173
    ANIMAL_LABEL_LIST: '/mnt/sdb/data/jingyinuo/mmnet/annotation/genus_to_id.csv'
    INPUT_CHANNEL_NUM: [3]
    INPUT_SIZE: 224
    RELATION_FILE: '/mnt/sdb/data/jingyinuo/mmnet/annotation/composition/relation.txt'
MODEL:
    ARCH: i3d
    MODEL_NAME: I3D
    RESUME: '/mnt/sdb/data/jingyinuo/results/animal_kingdom/I3D/I3D_8x8_R50.pkl'
    CONVERT_FROM_CAFFE2: False
RESNET:
    ZERO_INIT_FINAL_BN: True
    WIDTH_PER_GROUP: 64
    NUM_GROUPS: 1
    DEPTH: 50
    TRANS_FUNC: bottleneck_transform
    STRIDE_1X1: False
    NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
    LOCATION: [[[]], [[]], [[]], [[]]]
    GROUP: [[1], [1], [1], [1]]
    INSTANTIATION: softmax
TRAIN:
    BATCH_SIZE:  16
    LOSS: ce
    ACCUMULATION_STEPS: 4
    LR: 0.1
    EPOCHS: 100 ##
    MOMENTUM: 0.9
    WEIGHT_DECAY: 1e-4
    WARMUP_EPOCHS: 34.0
    OPTIMIZER: sgd
    LR_POLICY: cosine
BN:
    USE_PRECISE_STATS: True
    NUM_BATCHES_PRECISE: 100
    NORM_TYPE: sync_batchnorm
    NUM_SYNC_DEVICES: 1 #4
NUM_SHARDS: 1