DATA:
    ROOT: '/mnt/sdb/data/jingyinuo/mmnet/trimmed_video'
    TRAIN_FILE: '/mnt/sdb/data/jingyinuo/mmnet/annotation/composition/train.txt' #00 /mnt/sdb/data/jingyinuo/mmnet/annotation/composition/train.csv
    VAL_FILE: '/mnt/sdb/data/jingyinuo/mmnet/annotation/composition/test.txt'
    DATASET: mmnet
    NUM_FRAMES: 8
    NUM_CLASSES: 12
    LABEL_LIST: '/mnt/sdb/data/jingyinuo/mmnet/annotation/behavior_to_id.csv'
    MULTI_CLASSES: False
    NUM_ANIMAL_CLASSES: 173
    ANIMAL_LABEL_LIST: '/mnt/sdb/data/jingyinuo/mmnet/annotation/genus_to_id.csv'
    RELATION_FILE: '/mnt/sdb/data/jingyinuo/mmnet/annotation/composition/relation.txt'
MODEL:
    ARCH: ViT-B/16
    MODEL_NAME: 'XCLIP'
TRAIN:
    BATCH_SIZE:  16
    LOSS: 'ce'
    ACCUMULATION_STEPS: 4
    EPOCHS: 30