DATA:
    ROOT: '/mnt/sdb/data/jingyinuo/animal_kingdom/video'
    TRAIN_FILE: '/mnt/sdb/data/jingyinuo/animal_kingdom/train_all.txt' #00 train_all.txt
    VAL_FILE: '/mnt/sdb/data/jingyinuo/animal_kingdom/test_animal.txt' # test_animal
    DATASET: AK
    NUM_FRAMES: 8
    NUM_CLASSES: 140
    LABEL_LIST: '/mnt/sdb/data/jingyinuo/animal_kingdom/label.csv'
    MULTI_CLASSES: True
    NUM_ANIMAL_CLASSES: 958
    ANIMAL_LABEL_LIST: '/mnt/sdb/data/jingyinuo/animal_kingdom/animal_label.csv'
    # FEATURE_ROOT: '/mnt/sdb/data/jingyinuo/animal_kingdom/visual_feature'
MODEL:
    ARCH: ViT-B/16
    MODEL_NAME: 'EVL'
TRAIN:
    BATCH_SIZE:  64
    LOSS: 'ce'
    ACCUMULATION_STEPS: 4
    EPOCHS: 30
    LR: 4e-4
    LR_POLICY: cosineannealingwarmrestarts
    WEIGHT_DECAY: 0.05
    WEIGHT_DECAY_STEPS: 2e5
    WARMUP_EPOCHS: 4.0
    OPTIMIZER: adamw
NUM_WORKERS: 12