DATA:
    ROOT: '/mnt/sdb/data/jingyinuo/animal_kingdom/video'
    TRAIN_FILE: '/mnt/sdb/data/jingyinuo/animal_kingdom/train_all.txt' #00
    VAL_FILE: '/mnt/sdb/data/jingyinuo/animal_kingdom/test_animal.txt'
    DATASET: 'AK'
    NUM_FRAMES: 8
    NUM_CLASSES: 140
    LABEL_LIST: '/mnt/sdb/data/jingyinuo/animal_kingdom/label.csv'
    MULTI_CLASSES: True
    NUM_ANIMAL_CLASSES: 958
    ANIMAL_LABEL_LIST: '/mnt/sdb/data/jingyinuo/animal_kingdom/animal_label.csv'
    INPUT_CHANNEL_NUM: [3]
    INPUT_SIZE: 224
MODEL:
    ARCH: i3d
    DROPOUT_RATE: 0.5
    HEAD_ACT: sigmoid
    MODEL_NAME: 'X3D'
    OPTIMIZER: sgd
RESNET:
    ZERO_INIT_FINAL_BN: True
    TRANS_FUNC: x3d_transform
    STRIDE_1X1: False
X3D:
    WIDTH_FACTOR: 2.0
    DEPTH_FACTOR: 5.0
    BOTTLENECK_FACTOR: 2.25
    DIM_C5: 2048
    DIM_C1: 12
TRAIN:
    BATCH_SIZE:  16
    LOSS: ce
    ACCUMULATION_STEPS: 4
    EPOCHS: 30
    LR_POLICY: cosine
    OPTIMIZER: sgd
BN:
    USE_PRECISE_STATS: True
    NUM_BATCHES_PRECISE: 200
    NORM_TYPE: sync_batchnorm
    NUM_SYNC_DEVICES: 2 #4
    WEIGHT_DECAY: 0.0