DATA:
    ROOT: '/mnt/sdb/data/jingyinuo/animal_kingdom/video'
    TRAIN_FILE: '/mnt/sdb/data/jingyinuo/animal_kingdom/train_all.txt' #00
    VAL_FILE: '/mnt/sdb/data/jingyinuo/animal_kingdom/tsne/similarity.txt' # tsne_test_copy.txt
    DATASET: 'AK'
    NUM_FRAMES: 8
    NUM_CLASSES: 140
    LABEL_LIST: '/mnt/sdb/data/jingyinuo/animal_kingdom/label.csv'
    MULTI_CLASSES: True
    NUM_ANIMAL_CLASSES: 897
    ANIMAL_LABEL_LIST: '/mnt/sdb/data/jingyinuo/animal_kingdom/animal_label.csv'
    RELATION_FILE: '/mnt/sdb/data/jingyinuo/animal_kingdom/animal-action-relation.txt'
MODEL:
    ARCH: ViT-B/16
    MODEL_NAME: 'XCLIP'
TRAIN:
    BATCH_SIZE:  16
    LOSS: 'ce'
    ACCUMULATION_STEPS: 4
    EPOCHS: 30
TEST:
    TSNE: True
    TEST_LONG_TAIL: False
# AUG:
#     MIXUP: 0.0