DATA:
    ROOT: '/mnt/sdb/data/jingyinuo/LoTE-Animal/data'
    TRAIN_FILE: '/mnt/sdb/data/jingyinuo/LoTE-Animal/annotation/LoTE_train.txt' #00 /mnt/sdb/data/jingyinuo/mmnet/annotation/composition/train.csv
    VAL_FILE: '/mnt/sdb/data/jingyinuo/LoTE-Animal/annotation/LoTE_test.txt'
    DATASET: LoTE
    NUM_FRAMES: 8
    NUM_CLASSES: 21
    LABEL_LIST: '/mnt/sdb/data/jingyinuo/LoTE-Animal/annotation/LoTE_label.csv'
    MULTI_CLASSES: False
    NUM_ANIMAL_CLASSES: 11
    ANIMAL_LABEL_LIST: '/mnt/sdb/data/jingyinuo/LoTE-Animal/annotation/animal_label.csv'
    RELATION_FILE: '/mnt/sdb/data/jingyinuo/animal_kingdom/animal-action-relation.txt'
    # FEATURE_ROOT: '/mnt/sdb/data/jingyinuo/animal_kingdom/visual_feature'
MODEL:
    ARCH: ViT-B/16
    MODEL_NAME: 'EVL'
TRAIN:
    BATCH_SIZE:  64
    LOSS: 'ce'
    ACCUMULATION_STEPS: 4
    EPOCHS: 20
    LR: 4e-4
    LR_POLICY: cosineannealingwarmrestarts
    WEIGHT_DECAY: 0.05
    WEIGHT_DECAY_STEPS: 2e5
    WARMUP_EPOCHS: 4.0
    OPTIMIZER: adamw
NUM_WORKERS: 12